### ISSUE TITLE
Bug - blocks don't follow the timer

### ISSUE THREAD

**Issue by carteritos** [sk8ingDuck/MagicBlocks#1]
As you can see in your PlayerBlockPlaceEvent, you only take care of the block state so when state == 10 it will break the block indipendently of the time passed

**Comment by sk8ingDuck** [comment]
The time that the BukkitTask needs is defined by the config.getDestroyDelay(). 
It's not related to the block, the state counter will always be increased on each run and if the state is 10, it will cancel the task.
I don't see the problem?

**Comment by carteritos** [comment]
doing like so the block won't disappear after x seconds but just after state == 10, also the period in the task is in tick so you need to seconds * 20, i made a pull request, go compile that and see that now works like you wanted ! :)

**Comment by sk8ingDuck** [comment]
It's already working the way I want it to. 
"doing like so the block won't disappear after x seconds but just after state == 10" 
Yeah but state == 10 is reached after x seconds, so the block will disappear after x seconds?

You just renamed the 'state' variable to 'secondsElapsed' but that doesn't change the logic. And yes, the runTaskTimer method takes ticks and not seconds, but I made this on purpose so that you can set the time more precisely (and not only in seconds)
